version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      # Volume for user to mount their Google credentials JSON
      - ./credentials:/app/credentials
    depends_on:
      - db
    environment:
      # Override DATABASE_URL to use the PostgreSQL service
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/testdb
      # Other environment variables will be loaded from .env file

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
